### ISSUE TITLE
Can't move the GUI. Please help!

### ISSUE THREAD

**Issue by moneyfraud** [XBoom31/ApocalyseCheatsSC#59]
Noob here. So, when im in the Main menu, i can't move the GUI. When i'm in-game, i can only move the GUI if i have "Visuals" enabled. I play on 480p, and don't say to me that i need to change my resolution, My PC is shit, and i can't play on higher resolutions! Everything is appreaciated! Thanks.

**Comment by DarkAussieYT** [comment]
sorry to ask to change resolution but change from fullscreen or windowed into fullscreen windowed

**Comment by GenoSans** [comment]
normal.

**Comment by XBoom31** [comment]
I'll check the visuals loop to see if something it's related to the gui, if
is, you should just "delete the if" and it should work fine

On Sep 7, 2017 10:52, "GenoSans" <notifications@github.com> wrote:

normal.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/XBoom31/ApocalyseCheatsSC/issues/59#issuecomment-327719004>,
or mute the thread

**Comment by haxerro** [comment]
I have same problem here dont know whats going on ;v

**Comment by moneyfraud** [comment]
:/

**Comment by haxerro** [comment]
any1 know how to fix?

**Comment by moneyfraud** [comment]
Nope.
