### ISSUE TITLE
wtf..

### ISSUE THREAD

**Issue by moneyfraud** [XBoom31/ApocalyseCheatsSC#63]
I just want to ask, is this safe? I have been only using legitbot and visuals.. I got untrusted banned on 2 accs already. The issue is, is this actually UD? I have junk code, im using an ud injector that i changed the signature. I scrambled the DLL....

**Comment by XBoom31** [comment]
Don't use loadlib injectors

**Comment by moneyfraud** [comment]
loadlib injectors are the ones that are not driver injectors?

**Comment by DarkAussieYT** [comment]
untrusted ban is from your injector, or you have safe mode disabled

**Comment by moneyfraud** [comment]
safe mode is enabled by default. whats the difference between loadlib injectors and driver injectors?

**Comment by XBoom31** [comment]
Loadlib injectors are fucked, don't use them, paste a manual map 1

**Comment by ChillyLV** [comment]
Is this one any decent -> https://github.com/uItra/Injectora ?

**Comment by moneyfraud** [comment]
Can you recommend me one, please?

**Comment by XBoom31** [comment]
Private manual map

On Sep 15, 2017 17:49, "ChillyLV" <notifications@github.com> wrote:

Can you recommend me one, please?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/XBoom31/ApocalyseCheatsSC/issues/63#issuecomment-329804589>,
or mute the thread
